if (FALSE){
  
  "
  需要安装以下的包
  tibble
  Hmisc
  readr
  rJava
  xlsxjars
  dplyr
  stringr
  openxlsx
  pryr
  ggplot2
  patchwork
  mice
  glue
  tidyr
  RcppRoll
  plyr
  "
}

install.packages("tibble")
install.packages("Hmisc")
install.packages("readr")
install.packages("rJava")
install.packages("xlsxjars")
install.packages("dplyr")
install.packages("stringr")
install.packages("openxlsx")
install.packages("pryr")
install.packages("ggplot2")
install.packages("patchwork")
install.packages("mice")
install.packages("glue")
install.packages("tidyr")
install.packages("RcppRoll")
install.packages("plyr")